name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    name: Build
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...
    - name: Build
      run: go build -o casperin-${{matrix.os}} casperin.go
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: casperin-${{matrix.os}}
        path: casperin-${{matrix.os}}
